/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./supabase-enhanced";
export type PublicAuthType = z.infer<typeof generated.publicAuthTypeSchema>;
export type PublicIntegrationType = z.infer<
  typeof generated.publicIntegrationTypeSchema
>;
export type PublicStatus = z.infer<typeof generated.publicStatusSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicAssetsRow = z.infer<typeof generated.publicAssetsRowSchema>;
export type PublicAssetsInsert = z.infer<
  typeof generated.publicAssetsInsertSchema
>;
export type PublicAssetsUpdate = z.infer<
  typeof generated.publicAssetsUpdateSchema
>;
export type PublicIntegrationsRow = z.infer<
  typeof generated.publicIntegrationsRowSchema
>;
export type PublicIntegrationsInsert = z.infer<
  typeof generated.publicIntegrationsInsertSchema
>;
export type PublicIntegrationsUpdate = z.infer<
  typeof generated.publicIntegrationsUpdateSchema
>;
export type PublicNotificationsRow = z.infer<
  typeof generated.publicNotificationsRowSchema
>;
export type PublicNotificationsInsert = z.infer<
  typeof generated.publicNotificationsInsertSchema
>;
export type PublicNotificationsUpdate = z.infer<
  typeof generated.publicNotificationsUpdateSchema
>;
export type PublicNotificationsRelationships = z.infer<
  typeof generated.publicNotificationsRelationshipsSchema
>;
export type PublicOrganizationIntegrationsRow = z.infer<
  typeof generated.publicOrganizationIntegrationsRowSchema
>;
export type PublicOrganizationIntegrationsInsert = z.infer<
  typeof generated.publicOrganizationIntegrationsInsertSchema
>;
export type PublicOrganizationIntegrationsUpdate = z.infer<
  typeof generated.publicOrganizationIntegrationsUpdateSchema
>;
export type PublicOrganizationIntegrationsRelationships = z.infer<
  typeof generated.publicOrganizationIntegrationsRelationshipsSchema
>;
export type PublicOrganizationsRow = z.infer<
  typeof generated.publicOrganizationsRowSchema
>;
export type PublicOrganizationsInsert = z.infer<
  typeof generated.publicOrganizationsInsertSchema
>;
export type PublicOrganizationsUpdate = z.infer<
  typeof generated.publicOrganizationsUpdateSchema
>;
export type PublicPhasesRow = z.infer<typeof generated.publicPhasesRowSchema>;
export type PublicPhasesInsert = z.infer<
  typeof generated.publicPhasesInsertSchema
>;
export type PublicPhasesUpdate = z.infer<
  typeof generated.publicPhasesUpdateSchema
>;
export type PublicPhasesRelationships = z.infer<
  typeof generated.publicPhasesRelationshipsSchema
>;
export type PublicPinnedItemsRow = z.infer<
  typeof generated.publicPinnedItemsRowSchema
>;
export type PublicPinnedItemsInsert = z.infer<
  typeof generated.publicPinnedItemsInsertSchema
>;
export type PublicPinnedItemsUpdate = z.infer<
  typeof generated.publicPinnedItemsUpdateSchema
>;
export type PublicProductsRow = z.infer<
  typeof generated.publicProductsRowSchema
>;
export type PublicProductsInsert = z.infer<
  typeof generated.publicProductsInsertSchema
>;
export type PublicProductsUpdate = z.infer<
  typeof generated.publicProductsUpdateSchema
>;
export type PublicProductsRelationships = z.infer<
  typeof generated.publicProductsRelationshipsSchema
>;
export type PublicProfileKeysRow = z.infer<
  typeof generated.publicProfileKeysRowSchema
>;
export type PublicProfileKeysInsert = z.infer<
  typeof generated.publicProfileKeysInsertSchema
>;
export type PublicProfileKeysUpdate = z.infer<
  typeof generated.publicProfileKeysUpdateSchema
>;
export type PublicProfileKeysRelationships = z.infer<
  typeof generated.publicProfileKeysRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicProfilesRelationships = z.infer<
  typeof generated.publicProfilesRelationshipsSchema
>;
export type PublicProposalFollowersRow = z.infer<
  typeof generated.publicProposalFollowersRowSchema
>;
export type PublicProposalFollowersInsert = z.infer<
  typeof generated.publicProposalFollowersInsertSchema
>;
export type PublicProposalFollowersUpdate = z.infer<
  typeof generated.publicProposalFollowersUpdateSchema
>;
export type PublicProposalFollowersRelationships = z.infer<
  typeof generated.publicProposalFollowersRelationshipsSchema
>;
export type PublicProposalSettingsRow = z.infer<
  typeof generated.publicProposalSettingsRowSchema
>;
export type PublicProposalSettingsInsert = z.infer<
  typeof generated.publicProposalSettingsInsertSchema
>;
export type PublicProposalSettingsUpdate = z.infer<
  typeof generated.publicProposalSettingsUpdateSchema
>;
export type PublicProposalSettingsRelationships = z.infer<
  typeof generated.publicProposalSettingsRelationshipsSchema
>;
export type PublicProposalsRow = z.infer<
  typeof generated.publicProposalsRowSchema
>;
export type PublicProposalsInsert = z.infer<
  typeof generated.publicProposalsInsertSchema
>;
export type PublicProposalsUpdate = z.infer<
  typeof generated.publicProposalsUpdateSchema
>;
export type PublicProposalsRelationships = z.infer<
  typeof generated.publicProposalsRelationshipsSchema
>;
export type PublicSectionsRow = z.infer<
  typeof generated.publicSectionsRowSchema
>;
export type PublicSectionsInsert = z.infer<
  typeof generated.publicSectionsInsertSchema
>;
export type PublicSectionsUpdate = z.infer<
  typeof generated.publicSectionsUpdateSchema
>;
export type PublicSectionsRelationships = z.infer<
  typeof generated.publicSectionsRelationshipsSchema
>;
export type PublicTasksRow = z.infer<typeof generated.publicTasksRowSchema>;
export type PublicTasksInsert = z.infer<
  typeof generated.publicTasksInsertSchema
>;
export type PublicTasksUpdate = z.infer<
  typeof generated.publicTasksUpdateSchema
>;
export type PublicTasksRelationships = z.infer<
  typeof generated.publicTasksRelationshipsSchema
>;
export type PublicTicketsRow = z.infer<typeof generated.publicTicketsRowSchema>;
export type PublicTicketsInsert = z.infer<
  typeof generated.publicTicketsInsertSchema
>;
export type PublicTicketsUpdate = z.infer<
  typeof generated.publicTicketsUpdateSchema
>;
export type PublicTicketsRelationships = z.infer<
  typeof generated.publicTicketsRelationshipsSchema
>;
export type PublicVersionsRow = z.infer<
  typeof generated.publicVersionsRowSchema
>;
export type PublicVersionsInsert = z.infer<
  typeof generated.publicVersionsInsertSchema
>;
export type PublicVersionsUpdate = z.infer<
  typeof generated.publicVersionsUpdateSchema
>;
export type PublicVersionsRelationships = z.infer<
  typeof generated.publicVersionsRelationshipsSchema
>;
export type PublicCalculateTotalsRow = z.infer<
  typeof generated.publicCalculateTotalsRowSchema
>;
export type PublicProposalTotalsRow = z.infer<
  typeof generated.publicProposalTotalsRowSchema
>;
export type PublicConvertToManageArgs = z.infer<
  typeof generated.publicConvertToManageArgsSchema
>;
export type PublicConvertToManageReturns = z.infer<
  typeof generated.publicConvertToManageReturnsSchema
>;
export type PublicCopyVersionDataArgs = z.infer<
  typeof generated.publicCopyVersionDataArgsSchema
>;
export type PublicCopyVersionDataReturns = z.infer<
  typeof generated.publicCopyVersionDataReturnsSchema
>;
export type PublicCreateManageOpportunityArgs = z.infer<
  typeof generated.publicCreateManageOpportunityArgsSchema
>;
export type PublicCreateManageOpportunityReturns = z.infer<
  typeof generated.publicCreateManageOpportunityReturnsSchema
>;
export type PublicCreateManageProjectArgs = z.infer<
  typeof generated.publicCreateManageProjectArgsSchema
>;
export type PublicCreateManageProjectReturns = z.infer<
  typeof generated.publicCreateManageProjectReturnsSchema
>;
export type PublicCreateNewPhaseArgs = z.infer<
  typeof generated.publicCreateNewPhaseArgsSchema
>;
export type PublicCreateNewPhaseReturns = z.infer<
  typeof generated.publicCreateNewPhaseReturnsSchema
>;
export type PublicCreateNewProductArgs = z.infer<
  typeof generated.publicCreateNewProductArgsSchema
>;
export type PublicCreateNewProductReturns = z.infer<
  typeof generated.publicCreateNewProductReturnsSchema
>;
export type PublicCreateNewTaskArgs = z.infer<
  typeof generated.publicCreateNewTaskArgsSchema
>;
export type PublicCreateNewTaskReturns = z.infer<
  typeof generated.publicCreateNewTaskReturnsSchema
>;
export type PublicCreateNewTicketArgs = z.infer<
  typeof generated.publicCreateNewTicketArgsSchema
>;
export type PublicCreateNewTicketReturns = z.infer<
  typeof generated.publicCreateNewTicketReturnsSchema
>;
export type PublicCreateOpportunityProductsArgs = z.infer<
  typeof generated.publicCreateOpportunityProductsArgsSchema
>;
export type PublicCreateOpportunityProductsReturns = z.infer<
  typeof generated.publicCreateOpportunityProductsReturnsSchema
>;
export type PublicCreatePhaseTicketArgs = z.infer<
  typeof generated.publicCreatePhaseTicketArgsSchema
>;
export type PublicCreatePhaseTicketReturns = z.infer<
  typeof generated.publicCreatePhaseTicketReturnsSchema
>;
export type PublicCreateProjectPhaseArgs = z.infer<
  typeof generated.publicCreateProjectPhaseArgsSchema
>;
export type PublicCreateProjectPhaseReturns = z.infer<
  typeof generated.publicCreateProjectPhaseReturnsSchema
>;
export type PublicCreateTicketTaskArgs = z.infer<
  typeof generated.publicCreateTicketTaskArgsSchema
>;
export type PublicCreateTicketTaskReturns = z.infer<
  typeof generated.publicCreateTicketTaskReturnsSchema
>;
export type PublicDuplicatePhasesArgs = z.infer<
  typeof generated.publicDuplicatePhasesArgsSchema
>;
export type PublicDuplicatePhasesReturns = z.infer<
  typeof generated.publicDuplicatePhasesReturnsSchema
>;
export type PublicDuplicateProductsArgs = z.infer<
  typeof generated.publicDuplicateProductsArgsSchema
>;
export type PublicDuplicateProductsReturns = z.infer<
  typeof generated.publicDuplicateProductsReturnsSchema
>;
export type PublicDuplicateTasksArgs = z.infer<
  typeof generated.publicDuplicateTasksArgsSchema
>;
export type PublicDuplicateTasksReturns = z.infer<
  typeof generated.publicDuplicateTasksReturnsSchema
>;
export type PublicDuplicateTicketsArgs = z.infer<
  typeof generated.publicDuplicateTicketsArgsSchema
>;
export type PublicDuplicateTicketsReturns = z.infer<
  typeof generated.publicDuplicateTicketsReturnsSchema
>;
export type PublicGetMemberArgs = z.infer<
  typeof generated.publicGetMemberArgsSchema
>;
export type PublicGetMemberReturns = z.infer<
  typeof generated.publicGetMemberReturnsSchema
>;
export type PublicGetOpportunityProductsArgs = z.infer<
  typeof generated.publicGetOpportunityProductsArgsSchema
>;
export type PublicGetOpportunityProductsReturns = z.infer<
  typeof generated.publicGetOpportunityProductsReturnsSchema
>;
export type PublicGetOrganizationFromPhaseArgs = z.infer<
  typeof generated.publicGetOrganizationFromPhaseArgsSchema
>;
export type PublicGetOrganizationFromPhaseReturns = z.infer<
  typeof generated.publicGetOrganizationFromPhaseReturnsSchema
>;
export type PublicIsOrganizationMemberArgs = z.infer<
  typeof generated.publicIsOrganizationMemberArgsSchema
>;
export type PublicIsOrganizationMemberReturns = z.infer<
  typeof generated.publicIsOrganizationMemberReturnsSchema
>;
export type PublicIsProposalSharedArgs = z.infer<
  typeof generated.publicIsProposalSharedArgsSchema
>;
export type PublicIsProposalSharedReturns = z.infer<
  typeof generated.publicIsProposalSharedReturnsSchema
>;
export type PublicJsonbDiffValArgs = z.infer<
  typeof generated.publicJsonbDiffValArgsSchema
>;
export type PublicJsonbDiffValReturns = z.infer<
  typeof generated.publicJsonbDiffValReturnsSchema
>;
export type PublicPhaseLoopArgs = z.infer<
  typeof generated.publicPhaseLoopArgsSchema
>;
export type PublicPhaseLoopReturns = z.infer<
  typeof generated.publicPhaseLoopReturnsSchema
>;
export type PublicReadSecretArgs = z.infer<
  typeof generated.publicReadSecretArgsSchema
>;
export type PublicReadSecretReturns = z.infer<
  typeof generated.publicReadSecretReturnsSchema
>;
export type PublicSlugifyArgs = z.infer<
  typeof generated.publicSlugifyArgsSchema
>;
export type PublicSlugifyReturns = z.infer<
  typeof generated.publicSlugifyReturnsSchema
>;
export type PublicUnaccentArgs = z.infer<
  typeof generated.publicUnaccentArgsSchema
>;
export type PublicUnaccentReturns = z.infer<
  typeof generated.publicUnaccentReturnsSchema
>;
export type PublicUnaccentInitArgs = z.infer<
  typeof generated.publicUnaccentInitArgsSchema
>;
export type PublicUnaccentInitReturns = z.infer<
  typeof generated.publicUnaccentInitReturnsSchema
>;
export type PublicUpdateManageProductArgs = z.infer<
  typeof generated.publicUpdateManageProductArgsSchema
>;
export type PublicUpdateManageProductReturns = z.infer<
  typeof generated.publicUpdateManageProductReturnsSchema
>;
export type ReportingConversationsRow = z.infer<
  typeof generated.reportingConversationsRowSchema
>;
export type ReportingConversationsInsert = z.infer<
  typeof generated.reportingConversationsInsertSchema
>;
export type ReportingConversationsUpdate = z.infer<
  typeof generated.reportingConversationsUpdateSchema
>;
export type ReportingDashboardsRow = z.infer<
  typeof generated.reportingDashboardsRowSchema
>;
export type ReportingDashboardsInsert = z.infer<
  typeof generated.reportingDashboardsInsertSchema
>;
export type ReportingDashboardsUpdate = z.infer<
  typeof generated.reportingDashboardsUpdateSchema
>;
export type ReportingEngagementReservationsRow = z.infer<
  typeof generated.reportingEngagementReservationsRowSchema
>;
export type ReportingEngagementReservationsInsert = z.infer<
  typeof generated.reportingEngagementReservationsInsertSchema
>;
export type ReportingEngagementReservationsUpdate = z.infer<
  typeof generated.reportingEngagementReservationsUpdateSchema
>;
export type ReportingEngagementReservationsRelationships = z.infer<
  typeof generated.reportingEngagementReservationsRelationshipsSchema
>;
export type ReportingEngagementsRow = z.infer<
  typeof generated.reportingEngagementsRowSchema
>;
export type ReportingEngagementsInsert = z.infer<
  typeof generated.reportingEngagementsInsertSchema
>;
export type ReportingEngagementsUpdate = z.infer<
  typeof generated.reportingEngagementsUpdateSchema
>;
export type ReportingEngagementsRelationships = z.infer<
  typeof generated.reportingEngagementsRelationshipsSchema
>;
export type ReportingAbandonedConversationsByDayRow = z.infer<
  typeof generated.reportingAbandonedConversationsByDayRowSchema
>;
export type ReportingCallSummaryByPeriodRow = z.infer<
  typeof generated.reportingCallSummaryByPeriodRowSchema
>;
export type ReportingCallsByAgentRow = z.infer<
  typeof generated.reportingCallsByAgentRowSchema
>;
export type ReportingCallsByAgentByDayRow = z.infer<
  typeof generated.reportingCallsByAgentByDayRowSchema
>;
export type ReportingCallsSummaryByDayRow = z.infer<
  typeof generated.reportingCallsSummaryByDayRowSchema
>;
export type ReportingConversationsByAgentByDayRow = z.infer<
  typeof generated.reportingConversationsByAgentByDayRowSchema
>;
export type ReportingConversationsSummaryByDayRow = z.infer<
  typeof generated.reportingConversationsSummaryByDayRowSchema
>;
export type ReportingHandleTimeByDayRow = z.infer<
  typeof generated.reportingHandleTimeByDayRowSchema
>;
export type ReportingHandleTimeByDayTestRow = z.infer<
  typeof generated.reportingHandleTimeByDayTestRowSchema
>;
export type ReportingVoicemailsByDayRow = z.infer<
  typeof generated.reportingVoicemailsByDayRowSchema
>;
export type ReportingVoicemailsByMonthRow = z.infer<
  typeof generated.reportingVoicemailsByMonthRowSchema
>;
export type ReportingVoicemailsLeftByDayRow = z.infer<
  typeof generated.reportingVoicemailsLeftByDayRowSchema
>;
export type ReportingSearchNumberArgs = z.infer<
  typeof generated.reportingSearchNumberArgsSchema
>;
export type ReportingSearchNumberReturns = z.infer<
  typeof generated.reportingSearchNumberReturnsSchema
>;
export type UserExperienceViewsRow = z.infer<
  typeof generated.userExperienceViewsRowSchema
>;
export type UserExperienceViewsInsert = z.infer<
  typeof generated.userExperienceViewsInsertSchema
>;
export type UserExperienceViewsUpdate = z.infer<
  typeof generated.userExperienceViewsUpdateSchema
>;
export type TaskrouterBlacklistedPhoneNumbersRow = z.infer<
  typeof generated.taskrouterBlacklistedPhoneNumbersRowSchema
>;
export type TaskrouterBlacklistedPhoneNumbersInsert = z.infer<
  typeof generated.taskrouterBlacklistedPhoneNumbersInsertSchema
>;
export type TaskrouterBlacklistedPhoneNumbersUpdate = z.infer<
  typeof generated.taskrouterBlacklistedPhoneNumbersUpdateSchema
>;
export type TaskrouterTasksRow = z.infer<
  typeof generated.taskrouterTasksRowSchema
>;
export type TaskrouterTasksInsert = z.infer<
  typeof generated.taskrouterTasksInsertSchema
>;
export type TaskrouterTasksUpdate = z.infer<
  typeof generated.taskrouterTasksUpdateSchema
>;
export type SystemAnnotationTagEntityRow = z.infer<
  typeof generated.systemAnnotationTagEntityRowSchema
>;
export type SystemAnnotationTagEntityInsert = z.infer<
  typeof generated.systemAnnotationTagEntityInsertSchema
>;
export type SystemAnnotationTagEntityUpdate = z.infer<
  typeof generated.systemAnnotationTagEntityUpdateSchema
>;
export type SystemAuthIdentityRow = z.infer<
  typeof generated.systemAuthIdentityRowSchema
>;
export type SystemAuthIdentityInsert = z.infer<
  typeof generated.systemAuthIdentityInsertSchema
>;
export type SystemAuthIdentityUpdate = z.infer<
  typeof generated.systemAuthIdentityUpdateSchema
>;
export type SystemAuthIdentityRelationships = z.infer<
  typeof generated.systemAuthIdentityRelationshipsSchema
>;
export type SystemAuthProviderSyncHistoryRow = z.infer<
  typeof generated.systemAuthProviderSyncHistoryRowSchema
>;
export type SystemAuthProviderSyncHistoryInsert = z.infer<
  typeof generated.systemAuthProviderSyncHistoryInsertSchema
>;
export type SystemAuthProviderSyncHistoryUpdate = z.infer<
  typeof generated.systemAuthProviderSyncHistoryUpdateSchema
>;
export type SystemCredentialsEntityRow = z.infer<
  typeof generated.systemCredentialsEntityRowSchema
>;
export type SystemCredentialsEntityInsert = z.infer<
  typeof generated.systemCredentialsEntityInsertSchema
>;
export type SystemCredentialsEntityUpdate = z.infer<
  typeof generated.systemCredentialsEntityUpdateSchema
>;
export type SystemEventDestinationsRow = z.infer<
  typeof generated.systemEventDestinationsRowSchema
>;
export type SystemEventDestinationsInsert = z.infer<
  typeof generated.systemEventDestinationsInsertSchema
>;
export type SystemEventDestinationsUpdate = z.infer<
  typeof generated.systemEventDestinationsUpdateSchema
>;
export type SystemExecutionAnnotationTagsRow = z.infer<
  typeof generated.systemExecutionAnnotationTagsRowSchema
>;
export type SystemExecutionAnnotationTagsInsert = z.infer<
  typeof generated.systemExecutionAnnotationTagsInsertSchema
>;
export type SystemExecutionAnnotationTagsUpdate = z.infer<
  typeof generated.systemExecutionAnnotationTagsUpdateSchema
>;
export type SystemExecutionAnnotationTagsRelationships = z.infer<
  typeof generated.systemExecutionAnnotationTagsRelationshipsSchema
>;
export type SystemExecutionAnnotationsRow = z.infer<
  typeof generated.systemExecutionAnnotationsRowSchema
>;
export type SystemExecutionAnnotationsInsert = z.infer<
  typeof generated.systemExecutionAnnotationsInsertSchema
>;
export type SystemExecutionAnnotationsUpdate = z.infer<
  typeof generated.systemExecutionAnnotationsUpdateSchema
>;
export type SystemExecutionAnnotationsRelationships = z.infer<
  typeof generated.systemExecutionAnnotationsRelationshipsSchema
>;
export type SystemExecutionDataRow = z.infer<
  typeof generated.systemExecutionDataRowSchema
>;
export type SystemExecutionDataInsert = z.infer<
  typeof generated.systemExecutionDataInsertSchema
>;
export type SystemExecutionDataUpdate = z.infer<
  typeof generated.systemExecutionDataUpdateSchema
>;
export type SystemExecutionDataRelationships = z.infer<
  typeof generated.systemExecutionDataRelationshipsSchema
>;
export type SystemExecutionEntityRow = z.infer<
  typeof generated.systemExecutionEntityRowSchema
>;
export type SystemExecutionEntityInsert = z.infer<
  typeof generated.systemExecutionEntityInsertSchema
>;
export type SystemExecutionEntityUpdate = z.infer<
  typeof generated.systemExecutionEntityUpdateSchema
>;
export type SystemExecutionEntityRelationships = z.infer<
  typeof generated.systemExecutionEntityRelationshipsSchema
>;
export type SystemExecutionMetadataRow = z.infer<
  typeof generated.systemExecutionMetadataRowSchema
>;
export type SystemExecutionMetadataInsert = z.infer<
  typeof generated.systemExecutionMetadataInsertSchema
>;
export type SystemExecutionMetadataUpdate = z.infer<
  typeof generated.systemExecutionMetadataUpdateSchema
>;
export type SystemExecutionMetadataRelationships = z.infer<
  typeof generated.systemExecutionMetadataRelationshipsSchema
>;
export type SystemFolderRow = z.infer<typeof generated.systemFolderRowSchema>;
export type SystemFolderInsert = z.infer<
  typeof generated.systemFolderInsertSchema
>;
export type SystemFolderUpdate = z.infer<
  typeof generated.systemFolderUpdateSchema
>;
export type SystemFolderRelationships = z.infer<
  typeof generated.systemFolderRelationshipsSchema
>;
export type SystemFolderTagRow = z.infer<
  typeof generated.systemFolderTagRowSchema
>;
export type SystemFolderTagInsert = z.infer<
  typeof generated.systemFolderTagInsertSchema
>;
export type SystemFolderTagUpdate = z.infer<
  typeof generated.systemFolderTagUpdateSchema
>;
export type SystemFolderTagRelationships = z.infer<
  typeof generated.systemFolderTagRelationshipsSchema
>;
export type SystemInsightsByPeriodRow = z.infer<
  typeof generated.systemInsightsByPeriodRowSchema
>;
export type SystemInsightsByPeriodInsert = z.infer<
  typeof generated.systemInsightsByPeriodInsertSchema
>;
export type SystemInsightsByPeriodUpdate = z.infer<
  typeof generated.systemInsightsByPeriodUpdateSchema
>;
export type SystemInsightsByPeriodRelationships = z.infer<
  typeof generated.systemInsightsByPeriodRelationshipsSchema
>;
export type SystemInsightsMetadataRow = z.infer<
  typeof generated.systemInsightsMetadataRowSchema
>;
export type SystemInsightsMetadataInsert = z.infer<
  typeof generated.systemInsightsMetadataInsertSchema
>;
export type SystemInsightsMetadataUpdate = z.infer<
  typeof generated.systemInsightsMetadataUpdateSchema
>;
export type SystemInsightsMetadataRelationships = z.infer<
  typeof generated.systemInsightsMetadataRelationshipsSchema
>;
export type SystemInsightsRawRow = z.infer<
  typeof generated.systemInsightsRawRowSchema
>;
export type SystemInsightsRawInsert = z.infer<
  typeof generated.systemInsightsRawInsertSchema
>;
export type SystemInsightsRawUpdate = z.infer<
  typeof generated.systemInsightsRawUpdateSchema
>;
export type SystemInsightsRawRelationships = z.infer<
  typeof generated.systemInsightsRawRelationshipsSchema
>;
export type SystemInstalledNodesRow = z.infer<
  typeof generated.systemInstalledNodesRowSchema
>;
export type SystemInstalledNodesInsert = z.infer<
  typeof generated.systemInstalledNodesInsertSchema
>;
export type SystemInstalledNodesUpdate = z.infer<
  typeof generated.systemInstalledNodesUpdateSchema
>;
export type SystemInstalledNodesRelationships = z.infer<
  typeof generated.systemInstalledNodesRelationshipsSchema
>;
export type SystemInstalledPackagesRow = z.infer<
  typeof generated.systemInstalledPackagesRowSchema
>;
export type SystemInstalledPackagesInsert = z.infer<
  typeof generated.systemInstalledPackagesInsertSchema
>;
export type SystemInstalledPackagesUpdate = z.infer<
  typeof generated.systemInstalledPackagesUpdateSchema
>;
export type SystemInvalidAuthTokenRow = z.infer<
  typeof generated.systemInvalidAuthTokenRowSchema
>;
export type SystemInvalidAuthTokenInsert = z.infer<
  typeof generated.systemInvalidAuthTokenInsertSchema
>;
export type SystemInvalidAuthTokenUpdate = z.infer<
  typeof generated.systemInvalidAuthTokenUpdateSchema
>;
export type SystemMicrosoftGraphSubscriptionsRow = z.infer<
  typeof generated.systemMicrosoftGraphSubscriptionsRowSchema
>;
export type SystemMicrosoftGraphSubscriptionsInsert = z.infer<
  typeof generated.systemMicrosoftGraphSubscriptionsInsertSchema
>;
export type SystemMicrosoftGraphSubscriptionsUpdate = z.infer<
  typeof generated.systemMicrosoftGraphSubscriptionsUpdateSchema
>;
export type SystemMigrationsRow = z.infer<
  typeof generated.systemMigrationsRowSchema
>;
export type SystemMigrationsInsert = z.infer<
  typeof generated.systemMigrationsInsertSchema
>;
export type SystemMigrationsUpdate = z.infer<
  typeof generated.systemMigrationsUpdateSchema
>;
export type SystemProcessedDataRow = z.infer<
  typeof generated.systemProcessedDataRowSchema
>;
export type SystemProcessedDataInsert = z.infer<
  typeof generated.systemProcessedDataInsertSchema
>;
export type SystemProcessedDataUpdate = z.infer<
  typeof generated.systemProcessedDataUpdateSchema
>;
export type SystemProcessedDataRelationships = z.infer<
  typeof generated.systemProcessedDataRelationshipsSchema
>;
export type SystemProjectRow = z.infer<typeof generated.systemProjectRowSchema>;
export type SystemProjectInsert = z.infer<
  typeof generated.systemProjectInsertSchema
>;
export type SystemProjectUpdate = z.infer<
  typeof generated.systemProjectUpdateSchema
>;
export type SystemProjectRelationRow = z.infer<
  typeof generated.systemProjectRelationRowSchema
>;
export type SystemProjectRelationInsert = z.infer<
  typeof generated.systemProjectRelationInsertSchema
>;
export type SystemProjectRelationUpdate = z.infer<
  typeof generated.systemProjectRelationUpdateSchema
>;
export type SystemProjectRelationRelationships = z.infer<
  typeof generated.systemProjectRelationRelationshipsSchema
>;
export type SystemSettingsRow = z.infer<
  typeof generated.systemSettingsRowSchema
>;
export type SystemSettingsInsert = z.infer<
  typeof generated.systemSettingsInsertSchema
>;
export type SystemSettingsUpdate = z.infer<
  typeof generated.systemSettingsUpdateSchema
>;
export type SystemSharedCredentialsRow = z.infer<
  typeof generated.systemSharedCredentialsRowSchema
>;
export type SystemSharedCredentialsInsert = z.infer<
  typeof generated.systemSharedCredentialsInsertSchema
>;
export type SystemSharedCredentialsUpdate = z.infer<
  typeof generated.systemSharedCredentialsUpdateSchema
>;
export type SystemSharedCredentialsRelationships = z.infer<
  typeof generated.systemSharedCredentialsRelationshipsSchema
>;
export type SystemSharedWorkflowRow = z.infer<
  typeof generated.systemSharedWorkflowRowSchema
>;
export type SystemSharedWorkflowInsert = z.infer<
  typeof generated.systemSharedWorkflowInsertSchema
>;
export type SystemSharedWorkflowUpdate = z.infer<
  typeof generated.systemSharedWorkflowUpdateSchema
>;
export type SystemSharedWorkflowRelationships = z.infer<
  typeof generated.systemSharedWorkflowRelationshipsSchema
>;
export type SystemTagEntityRow = z.infer<
  typeof generated.systemTagEntityRowSchema
>;
export type SystemTagEntityInsert = z.infer<
  typeof generated.systemTagEntityInsertSchema
>;
export type SystemTagEntityUpdate = z.infer<
  typeof generated.systemTagEntityUpdateSchema
>;
export type SystemTestCaseExecutionRow = z.infer<
  typeof generated.systemTestCaseExecutionRowSchema
>;
export type SystemTestCaseExecutionInsert = z.infer<
  typeof generated.systemTestCaseExecutionInsertSchema
>;
export type SystemTestCaseExecutionUpdate = z.infer<
  typeof generated.systemTestCaseExecutionUpdateSchema
>;
export type SystemTestCaseExecutionRelationships = z.infer<
  typeof generated.systemTestCaseExecutionRelationshipsSchema
>;
export type SystemTestRunRow = z.infer<typeof generated.systemTestRunRowSchema>;
export type SystemTestRunInsert = z.infer<
  typeof generated.systemTestRunInsertSchema
>;
export type SystemTestRunUpdate = z.infer<
  typeof generated.systemTestRunUpdateSchema
>;
export type SystemTestRunRelationships = z.infer<
  typeof generated.systemTestRunRelationshipsSchema
>;
export type SystemUserRow = z.infer<typeof generated.systemUserRowSchema>;
export type SystemUserInsert = z.infer<typeof generated.systemUserInsertSchema>;
export type SystemUserUpdate = z.infer<typeof generated.systemUserUpdateSchema>;
export type SystemUserApiKeysRow = z.infer<
  typeof generated.systemUserApiKeysRowSchema
>;
export type SystemUserApiKeysInsert = z.infer<
  typeof generated.systemUserApiKeysInsertSchema
>;
export type SystemUserApiKeysUpdate = z.infer<
  typeof generated.systemUserApiKeysUpdateSchema
>;
export type SystemUserApiKeysRelationships = z.infer<
  typeof generated.systemUserApiKeysRelationshipsSchema
>;
export type SystemVariablesRow = z.infer<
  typeof generated.systemVariablesRowSchema
>;
export type SystemVariablesInsert = z.infer<
  typeof generated.systemVariablesInsertSchema
>;
export type SystemVariablesUpdate = z.infer<
  typeof generated.systemVariablesUpdateSchema
>;
export type SystemWebhookEntityRow = z.infer<
  typeof generated.systemWebhookEntityRowSchema
>;
export type SystemWebhookEntityInsert = z.infer<
  typeof generated.systemWebhookEntityInsertSchema
>;
export type SystemWebhookEntityUpdate = z.infer<
  typeof generated.systemWebhookEntityUpdateSchema
>;
export type SystemWebhookEntityRelationships = z.infer<
  typeof generated.systemWebhookEntityRelationshipsSchema
>;
export type SystemWorkflowEntityRow = z.infer<
  typeof generated.systemWorkflowEntityRowSchema
>;
export type SystemWorkflowEntityInsert = z.infer<
  typeof generated.systemWorkflowEntityInsertSchema
>;
export type SystemWorkflowEntityUpdate = z.infer<
  typeof generated.systemWorkflowEntityUpdateSchema
>;
export type SystemWorkflowEntityRelationships = z.infer<
  typeof generated.systemWorkflowEntityRelationshipsSchema
>;
export type SystemWorkflowHistoryRow = z.infer<
  typeof generated.systemWorkflowHistoryRowSchema
>;
export type SystemWorkflowHistoryInsert = z.infer<
  typeof generated.systemWorkflowHistoryInsertSchema
>;
export type SystemWorkflowHistoryUpdate = z.infer<
  typeof generated.systemWorkflowHistoryUpdateSchema
>;
export type SystemWorkflowHistoryRelationships = z.infer<
  typeof generated.systemWorkflowHistoryRelationshipsSchema
>;
export type SystemWorkflowStatisticsRow = z.infer<
  typeof generated.systemWorkflowStatisticsRowSchema
>;
export type SystemWorkflowStatisticsInsert = z.infer<
  typeof generated.systemWorkflowStatisticsInsertSchema
>;
export type SystemWorkflowStatisticsUpdate = z.infer<
  typeof generated.systemWorkflowStatisticsUpdateSchema
>;
export type SystemWorkflowStatisticsRelationships = z.infer<
  typeof generated.systemWorkflowStatisticsRelationshipsSchema
>;
export type SystemWorkflowsTagsRow = z.infer<
  typeof generated.systemWorkflowsTagsRowSchema
>;
export type SystemWorkflowsTagsInsert = z.infer<
  typeof generated.systemWorkflowsTagsInsertSchema
>;
export type SystemWorkflowsTagsUpdate = z.infer<
  typeof generated.systemWorkflowsTagsUpdateSchema
>;
export type SystemWorkflowsTagsRelationships = z.infer<
  typeof generated.systemWorkflowsTagsRelationshipsSchema
>;
